guard_config:
  max_guards: 5
  min_radius: 5
  max_radius: 30
  respawn_time: 120
  cooldown_place: 5
  heal_amount: 20
  show_health_bar: true
  show_detection_effect: true
  min_detection_radius: 8
  max_detection_radius: 25

  guard_types:
    tier1:
      perm: "guard.tier.1"
      tier: 1
      hp: 120
      dmg: 9
      heal: true
      name: "Новобранец"           # ✅ Железный голем
      radius: 12
      icon: "IRON_INGOT"
      price: 1500

    tier2:
      perm: "guard.tier.2"
      tier: 2
      hp: 200
      dmg: 14
      heal: true
      name: "Морозный Страж"        # ✅ Stray (скелет с луком)
      radius: 16
      icon: "GOLD_INGOT"
      price: 6000

    tier3:
      perm: "guard.tier.3"
      tier: 3
      hp: 350
      dmg: 20
      heal: true
      name: "Иссушенный Страж"      # ✅ Wither Skeleton
      radius: 20
      icon: "DIAMOND"
      price: 18000

    tier4:
      perm: "guard.tier.4"
      tier: 4
      hp: 550
      dmg: 28
      heal: true
      name: "Элитный Страж"         # ✅ Pillager (арбалетчик)
      radius: 24
      icon: "EMERALD"
      price: 45000

    tier5:
      perm: "guard.tier.5"
      tier: 5
      hp: 900
      dmg: 40
      heal: true
      name: "Легендарный Страж"     # ✅ Vindicator (палач)
      radius: 30
      icon: "NETHERITE_INGOT"
      price: 120000

  territory:
    require_territory: true
    allow_in_wilderness: false
    check_build_permission: true