guard_config:
  max_guards: 3
  min_radius: 3
  max_radius: 20
  respawn_time: 60
  cooldown_place: 10
  heal_amount: 10
  show_health_bar: true
  show_detection_effect: true
  min_detection_radius: 5
  max_detection_radius: 20

  # Настройки размеров стражей
  guard_sizes:
    1: 1.0  # Новичок - обычный размер
    2: 1.2  # Воин - чуть больше
    3: 1.4  # Рыцарь - заметно больше
    4: 1.6  # Элитный - очень большой
    5: 2.0  # Легенда - гигант

  guard_types:
    1:
      perm: "guard.type.i"
      hp: 100
      dmg: 10
      heal: true
      name: "Новичок"
      tier: 1
      radius: 10
      icon: "WOODEN_SWORD"
      price: 1000
    2:
      perm: "guard.type.ii"
      hp: 200
      dmg: 15
      heal: true
      name: "Воин"
      tier: 2
      radius: 15
      icon: "STONE_SWORD"
      price: 5000
    3:
      perm: "guard.type.iii"
      hp: 350
      dmg: 20
      heal: true
      name: "Рыцарь"
      tier: 3
      radius: 20
      icon: "IRON_SWORD"
      price: 15000
    4:
      perm: "guard.type.iv"
      hp: 500
      dmg: 25
      heal: true
      name: "Элитный"
      tier: 4
      radius: 25
      icon: "DIAMOND_SWORD"
      price: 30000
    5:
      perm: "guard.type.v"
      hp: 750
      dmg: 35
      heal: true
      name: "Легенда"
      tier: 5
      radius: 30
      icon: "NETHERITE_SWORD"
      price: 50000

  territory:
    require_territory: true  # Включить проверку территории
    allow_in_wilderness: false  # Разрешить в дикой местности
    check_build_permission: true  # Проверять права на строительство

